#' Generate a tree summarizing the dataset structure, based on measurement types and event remarks.
#'
#' @param event
#' @param measurement
#' @return
#' @export
treeStructure <- function(event, measurement) {

  # events table

  if ("occurrenceID" %in% names(measurement)) {
    measurement <- measurement %>% filter(is.na(occurrenceID))
  }
  measurement <- measurement %>% group_by(eventID) %>% summarize(types = paste0(sort(unique(measurementType)), collapse = ", "))
  if ("type" %in% names(event)) {
    event <- event %>% select(eventID, parentEventID, type)
  } else {
    event <- event %>% select(eventID, parentEventID)
  }

  event <- left_join(event,  measurement, by = "eventID")
  event$parentEventID[is.na(event$parentEventID)] <- "dummy"
  event$types[is.na(event$types)] <- " "

  # clean up events

  parentids <- unique(event$parentEventID)
  event$leaf <- !event$eventID %in% parentids

  if ("type" %in% names(event)) {
    leafs <- event %>% filter(leaf) %>% group_by(parentEventID, types, type) %>% summarize(eventID = first(eventID), records = n())
  } else {
    leafs <- event %>% filter(leaf) %>% group_by(parentEventID, types) %>% summarize(eventID = first(eventID), records = n())
  }
  stems <- event %>% filter(!leaf) %>% mutate(records = 1)
  cleanevents <- bind_rows(stems, leafs) %>% select(-leaf) %>% arrange(eventID)

  # hash events

  cleanevents$hash <- NA

  dict <- new.env()
  for (i in 1:nrow(cleanevents)) {
    entry <- list()
    types <- cleanevents$types[i]
    entry$types <- types
    entry$example <- example
    if ("type" %in% names(cleanevents)) {
      types <- paste0(types, cleanevents$type[i], collapse = ";")
      entry$type <- cleanevents$type[i]
    } else {
      entry$type <- ""
    }
    hash <- digest(types, algo = "sha1")
    dict[[hash]] <- entry
    cleanevents$hash[i] <- hash
  }

  cleanevents <- cleanevents %>% select(c("eventID", "parentEventID", "records", "hash"))

  # construct event tree

  eventtree <- FromDataFrameNetwork(cleanevents, check = "no-check")
  eventtree$hash <- " "
  eventtree$records <- 0

  # construct summary tree

  paths <- eventtree$Get(function(node) { return(c(node$level, node$hash, node$records)) }, simplify = FALSE)
  tree <- NULL
  history <- list()

  for (i in 1:length(paths)) {

    level <- as.integer(paths[i][[1]][1])
    hash <- paths[i][[1]][2]
    records <- as.integer(paths[i][[1]][3])
    example <- names(paths[i])

    # reconstruct complete path
    if (level <= length(history)) {
      for (j in seq(length(history), level, by = -1)) {
        history[[j]] <- NULL
      }
    }
    history[[level]] <- hash

    if (level == 1) {
      tree <- Node$new(hash)
    } else {

      # check if current path exists
      path <- unlist(history)[2:length(history)]
      result <- tree$Climb(name = path)

      if (is.null(result)) {
        # path does not exist, so go back one level
        if (length(path) > 1) {
          parent <- tree$Climb(name = head(path, -1))
        } else {
          parent <- tree
        }
        child <- parent$AddChild(hash)
        child$records <- records
        child$example <- example
      } else {
        # exists, increase
        result$records <- result$records + records
      }
    }
  }

  return(list(tree = tree, dict = dict))

}

#' Print a tree generated by treeStructure().
#'
#' @param tree
#' @param dict
#' @export
printTree <- function(tree, dict) {

  nodes <- tree$Get(function(node) {
    hash <- node$name
    level <- node$level
    records <- node$records
    example <- node$example
    prop <- dict[[hash]]
    return(list(level = level, hash = hash, records = records, example = example, type = prop$type, types = prop$types))
  }, simplify = FALSE)

  for (n in nodes) {
    indent <- paste0(rep(" ", (n$level - 1) * 2), collapse = "")
    sindent <- paste0(rep(" ", (n$level - 1) * 2), collapse = "")
    out <- paste0(
      indent,
      " ### Level ",
      n$level,
      " ###\n    ",
      sindent,
      " event type: ",
      n$type,
      "\n    ",
      sindent,
      " example: ",
      n$example,
      "\n    ",
      sindent,
      " measurement types: ",
      n$types,
      "\n    ",
      sindent,
      " records: ",
      n$records,
      collapse = ""
    )
    message(out)
  }

}

